# This file has been generated by the Catala compiler, do not edit!

from catala_runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum
from . import Stdlib_en as stdlib_en
from . import Date_en as date_en
from . import Period_en as period_en
from . import Money_en as money_en
from . import Integer_en as integer_en
from . import Decimal_en as decimal_en
from . import List_en as list_en

class S:
    def __init__(self, o: Optional[Integer]) -> None:
        self.o = o

    def __eq__(self, other: object) -> bool:
        if isinstance(other, S):
            return (self.o == other.o)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "S(o={})".format(self.o)

class SIn:
    def __init__(self, ) -> None:
        pass

    def __eq__(self, other: object) -> bool:
        if isinstance(other, SIn):
            return (True)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "SIn()".format()


def s(s_in:SIn):
    pos = (SourcePosition(filename="tests/default/good/python_opt.catala_en",
               start_line=10, start_column=22, end_line=10, end_column=28,
               law_headings=[]))
    o__2 = ((None, pos))
    if o__2 is None:
        pos__1 = (SourcePosition(
                      filename="tests/default/good/python_opt.catala_en",
                      start_line=8, start_column=23,
                      end_line=8, end_column=41, law_headings=[]))
        o__1 = ((integer_of_string("42"), pos__1))
    else:
        o__1 = (o__2)
    if o__1 is None:
        pos__1 = (SourcePosition(
                      filename="tests/default/good/python_opt.catala_en",
                      start_line=5, start_column=10,
                      end_line=5, end_column=11, law_headings=[]))
        raise NoValue(pos__1)
    else:
        o = (o__1[0])
    return S(o = o)

# Automatic Catala tests
if __name__ == "__main__":
  s_test = (s(SIn()))
  print("\x1b[32m[RESULT]\x1b[m Scope S executed successfully.")
