(library
 (name clerk_driver)
 (public_name catala.clerk_driver)
 (libraries
  ;;  runtime_ocaml
  catala.catala_utils
  catala.surface
  catala.clerk_lib
  catala.clerk_backend
  clerk_utils
  ninja_utils
  cmdliner
  re
  ocolor
  otoml
  yojson)
 (modules clerk_report clerk_runtest clerk_coverage clerk_rules clerk_driver))

(rule
 (target custom_linking.sexp)
 (mode fallback)
 (action
  (with-stdout-to
   %{target}
   (echo "()"))))

(executable
 (name clerk)
 (public_name clerk)
 (flags
  (:standard
   (:include custom_linking.sexp)))
 ; These are actually runtime deps and not link deps
 (link_deps
  %{bin:catala}
  (alias ../runtimes/runtimes))
 (libraries clerk_driver)
 (modules clerk)
 (package catala))

(alias
 (name clerk)
 (deps %{bin:clerk} %{bin:catala}))

(rule
 (targets (dir cmdliner-support))
 (deps clerk.exe)
 (action
  (ignore-stdout
   (run cmdliner install tool-support ./clerk.exe:clerk cmdliner-support))))

(install
 (section man)
 (package catala)
 (files
  (glob_files_rec ./cmdliner-support/share/man/*.1)
  ))
